package manual;

public enum LexicalClass {
    OPERATOR_ADD,
    OPERATOR_MINUS,
    OPERATOR_DIV,
    OPERATOR_MUL,
    OPERATOR_LESS_THAN,
    OPERATOR_LESS_EQUAL_THAN,
    OPERATOR_GREATER_THAN,
    OPERATOR_GREATER_EQUAL_THAN,
    OPERATOR_EQUAL,
    OPERATOR_NOT_EQUAL,
    OPERATOR_ASSIGNMENT,
    INTEGER_NUM,
    REAL_NUM,
    VAR_NAME,
    EOI,
    EOD,
    OPEN_PARENTHESIS,
    CLOSE_PARENTHESIS,
    IGNORABLE,
    EOF //This is needed for the syntactical parser
}
