/* Generated By:JavaCC: Do not edit this line. SynacticParserConstants.java */
package syntacticParser.auto.descentVersion;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SynacticParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int chr = 1;
  /** RegularExpression Id. */
  int digit = 2;
  /** RegularExpression Id. */
  int posDigit = 3;
  /** RegularExpression Id. */
  int enter0 = 4;
  /** RegularExpression Id. */
  int flt = 5;
  /** RegularExpression Id. */
  int sign = 6;
  /** RegularExpression Id. */
  int exp = 7;
  /** RegularExpression Id. */
  int num_ent = 10;
  /** RegularExpression Id. */
  int num_real = 11;
  /** RegularExpression Id. */
  int tipo = 12;
  /** RegularExpression Id. */
  int b00lean = 13;
  /** RegularExpression Id. */
  int opE4 = 14;
  /** RegularExpression Id. */
  int opE1 = 15;
  /** RegularExpression Id. */
  int opE2 = 16;
  /** RegularExpression Id. */
  int opE3 = 17;
  /** RegularExpression Id. */
  int opAdd = 18;
  /** RegularExpression Id. */
  int opMinus = 19;
  /** RegularExpression Id. */
  int nom_var = 20;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<chr>",
    "<digit>",
    "<posDigit>",
    "<enter0>",
    "<flt>",
    "<sign>",
    "<exp>",
    "<token of kind 8>",
    "<token of kind 9>",
    "<num_ent>",
    "<num_real>",
    "<tipo>",
    "<b00lean>",
    "\"not\"",
    "<opE1>",
    "<opE2>",
    "<opE3>",
    "\"+\"",
    "\"-\"",
    "<nom_var>",
    "\"&&\"",
    "\";\"",
    "\"=\"",
    "\"(\"",
    "\")\"",
  };

}
